<?php
error_reporting(E_ALL);
ini_set('display_errors', 'on');
include_once("db.php");

// $db = new DB();

// $uprecipe = [
//         'title' => addslashes($_POST['title']),
//         'time' => addslashes($_POST['time']),
//         'ingredients' => addslashes($_POST['ingredients']),
//         'directions' => addslashes($_POST['directions'])
//     ];

// $recipe_results = $db->execute("SELECT title FROM recipe WHERE recipe_id = $recipe_id");
// function updateRecipe($table_name, $updaterecipe, $recipe) {

    // $updaterecipe = "
    // UPDATE recipe 
    // SET title = $title,
    //     time = $time,
    //     ingredients = $ingredients,
    //     directions = $directions,
    // WHERE recipe_id = {$_SESSION['user_id']}
    // ";
    // $db = new DB();
    // $db->execute($updaterecipe);
  

     // $db->updaterecipe('recipe', $uprecipe, 'recipe_id');


?>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>View</title>
    <link rel="stylesheet" href="index.css">
    <link rel="stylesheet" href="animate.css">
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Oxygen:300' rel='stylesheet' type='text/css'>
    <script src="jqimport.js"></script>
    <script src="main.js"></script>
</head>
<body>
    

    <div class="form viewContent">
            <h2 class="titles">your specific title goes here via php/db</h2>
            <span>Time:</span>
            <div>
                <p>Will be generated by php/database</p>
            </div>    
            <span>Ingredients:</span>
            <div>
                <p>Will be generated by php/database</p>
            </div>  
            <span>Directions:</span>
            <div>
                <p>Will be generated by php/database</p>
            </div>  
            <div class="buttons">
                <button class="edit">Edit</button>
            </div>    
    </div>
</body>
</html>